import "./globals.scss";
import { Inter, Merriweather } from "next/font/google";
import NavBar from "./components/navBar/navBar";
import Footer from "./components/footer/footer";

const merriweather = Merriweather({
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata = {
    title: "Academia Pi",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={merriweather.className}>
                <NavBar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
