import "./globals.scss";
import { Merriweather } from "next/font/google";
import Provider from "./components/Provider";

const merriweather = Merriweather({
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata = {
    title: "Academia Pi",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={merriweather.className}>
                <Provider>
                    <main className="app">{children}</main>
                </Provider>
            </body>
        </html>
    );
}
